// Marcas y modelos populares para el datalist del admin.
// Si el usuario escribe una marca/modelo nuevo, el datalist no lo
// limita: es solo una sugerencia (el input acepta texto libre).
module.exports = {
  'Audi':           ['A1','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4 e-tron','Q5','Q7','Q8','e-tron','e-tron GT','R8','RS3','RS4','RS5','RS6','RS7','S3','S4','S5','S6','S8','TT','TT RS'],
  'BMW':            ['Serie 1','Serie 2','Serie 3','Serie 4','Serie 5','Serie 6','Serie 7','Serie 8','X1','X2','X3','X4','X5','X6','X7','Z4','i3','i4','i5','i7','iX','iX1','iX3','M2','M3','M4','M5','M8'],
  'Mercedes-Benz':  ['Clase A','Clase B','Clase C','Clase E','Clase S','CLA','CLS','GLA','GLB','GLC','GLE','GLS','EQA','EQB','EQC','EQE','EQS','AMG GT','SL','SLC','G','Vito','Sprinter','V-Class','Marco Polo'],
  'Volkswagen':     ['Polo','Golf','Passat','Arteon','Tiguan','T-Roc','T-Cross','Taigo','Touareg','Touran','ID.3','ID.4','ID.5','ID.7','ID. Buzz','Beetle','Caddy','Transporter','Multivan','California','Crafter'],
  'Toyota':         ['Aygo','Aygo X','Yaris','Yaris Cross','Corolla','Corolla Cross','C-HR','RAV4','Highlander','Land Cruiser','Hilux','Camry','Prius','GR Yaris','GR Corolla','GR86','GR Supra','ProAce','ProAce City'],
  'Renault':        ['Twingo','Clio','Captur','Megane','Megane E-Tech','Arkana','Austral','Espace','Scénic','Scenic E-Tech','Kangoo','Trafic','Master','Zoe','Rafale'],
  'Peugeot':        ['208','308','408','508','2008','3008','5008','Partner','Rifter','Expert','Traveller','Boxer','e-208','e-308','e-2008','e-3008','e-5008'],
  'Ford':           ['Fiesta','Focus','Kuga','Puma','Mondeo','Mustang','Mustang Mach-E','Edge','Explorer','S-Max','Galaxy','Ranger','Transit','Tourneo Connect','Tourneo Custom','Bronco','Maverick','F-150','GT'],
  'Citroën':        ['C1','C3','C3 Aircross','C4','C4 X','C5 Aircross','C5 X','Berlingo','SpaceTourer','Jumpy','Jumper','ë-C3','ë-C4'],
  'Opel':           ['Corsa','Astra','Mokka','Crossland','Grandland','Insignia','Combo','Combo Life','Vivaro','Vivaro Life','Movano','Zafira','Zafira Life'],
  'SEAT':           ['Ibiza','Leon','Arona','Ateca','Tarraco','Mii','Alhambra'],
  'Cupra':          ['Born','Formentor','Leon','Ateca','Tavascan','Terramar'],
  'Skoda':          ['Fabia','Octavia','Superb','Kamiq','Karoq','Kodiaq','Scala','Enyaq','Elroq'],
  'Volvo':          ['XC40','XC60','XC90','S60','S90','V60','V90','EX30','EX40','EX90','C40'],
  'Hyundai':        ['i10','i20','i30','Tucson','Kona','Santa Fe','Bayon','Ioniq','Ioniq 5','Ioniq 6','Staria'],
  'Kia':            ['Picanto','Rio','Ceed','ProCeed','XCeed','Stonic','Sportage','Sorento','Niro','Niro EV','EV3','EV6','EV9','Soul'],
  'Nissan':         ['Micra','Juke','Qashqai','X-Trail','Ariya','Leaf','Navara','Townstar','Interstar'],
  'Mazda':          ['2','3','6','CX-3','CX-30','CX-5','CX-60','CX-80','MX-30','MX-5'],
  'Fiat':           ['500','500e','500X','500L','Panda','Tipo','Ducato','Doblo','Talento','600','600e','Pulse','Topolino'],
  'Alfa Romeo':     ['Giulia','Stelvio','Tonale','Giulietta','MiTo','Junior','4C'],
  'Jeep':           ['Renegade','Compass','Wrangler','Cherokee','Grand Cherokee','Avenger','Gladiator','Wagoneer'],
  'Land Rover':     ['Defender','Discovery','Discovery Sport','Range Rover','Range Rover Sport','Range Rover Evoque','Range Rover Velar'],
  'Jaguar':         ['F-Pace','E-Pace','I-Pace','XE','XF','F-Type'],
  'Porsche':        ['911','718 Cayman','718 Boxster','Macan','Cayenne','Panamera','Taycan'],
  'Tesla':          ['Model 3','Model S','Model X','Model Y','Cybertruck','Roadster'],
  'Honda':          ['Civic','Jazz','HR-V','CR-V','ZR-V','e:Ny1','e'],
  'Mitsubishi':     ['ASX','Eclipse Cross','Outlander','L200','Space Star','Colt'],
  'Suzuki':         ['Swift','Vitara','S-Cross','Ignis','Jimny','Across','Swace','Baleno'],
  'Dacia':          ['Sandero','Sandero Stepway','Logan','Duster','Spring','Jogger','Bigster'],
  'Mini':           ['Cooper','Cooper SE','Cooper Convertible','Countryman','Clubman','Aceman','John Cooper Works'],
  'Lexus':          ['UX','NX','RX','LX','LC','ES','LBX','RZ','LS'],
  'Smart':          ['ForTwo','ForFour','#1','#3','#5'],
  'DS':             ['DS 3','DS 4','DS 7','DS 9','DS 3 Crossback'],
  'Maserati':       ['Ghibli','Quattroporte','Levante','Grecale','MC20','GranTurismo','GranCabrio'],
  'Bentley':        ['Continental GT','Flying Spur','Bentayga'],
  'Aston Martin':   ['Vantage','DB11','DB12','DBS','DBX'],
  'Lamborghini':    ['Huracán','Urus','Revuelto','Temerario'],
  'Ferrari':        ['Roma','296','SF90','F8','Purosangue','12Cilindri','Daytona SP3'],
  'Rolls-Royce':    ['Ghost','Phantom','Cullinan','Spectre','Wraith'],
  'McLaren':        ['Artura','750S','GT','Senna','P1'],
  'MG':             ['MG3','MG4','MG5','ZS','HS','Marvel R','Cyberster','EHS'],
  'Subaru':         ['Forester','Outback','Impreza','XV','Crosstrek','BRZ','Solterra'],
  'Lancia':         ['Ypsilon'],
  'Chevrolet':      ['Camaro','Corvette','Silverado','Suburban','Tahoe','Trax'],
  'Dodge':          ['Charger','Challenger','Durango','Ram 1500','Ram 2500'],
  'Cadillac':       ['Escalade','CT5','XT5','XT6','Lyriq'],
  'Lincoln':        ['Navigator','Aviator','Nautilus'],
  'GMC':            ['Yukon','Sierra','Hummer EV'],
  'Pontiac':        ['Firebird','GTO','Trans Am'],
  'Buick':          ['Encore','Enclave','LaCrosse']
};
